#!/usr/bin/env bash

set -exuo pipefail

VERSION="prerelease-$(echo $GITHUB_SHA | cut -c1-7)"
echo $VERSION
zip ${VERSION}.xpi manifest.json mysources.js options/*
gh release create --prerelease $VERSION ${VERSION}.xpi