on: 
  push: 
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    - env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        VERSION="prerelease-$(echo "${{ github.sha }}" | cut -c1-7)"
        echo $VERSION
        zip $VERSION.xpi manifest.json content_script.js options/*
        gh release create --prerelease create $VERSION $VERSION.xpi
