on: 
  push:
    tags:
    - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    - run: zip mysources.xpi manifest.json content_script.json options/*
    - run: gh release create $(echo "${{ github.event.ref }}" | rev | cut -d/ -f1) mysources.xpi
