on: 
  push:
    tags:
    - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    - env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        VERSION="$(echo "${{ github.ref }}" | rev | cut -d/ -f1 | rev)"
        echo $VERSION
        zip $VERSION.xpi manifest.json content_script.js options/*
        gh release create $VERSION $VERSION.xpi
