on: 
  push:
    tags:
    - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    - env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: ./cmd/release
