on: 
  push:
    tags:
    - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    - env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        VERSIONED_FILE="$(echo "${{ github.event.ref }}" | rev | cut -d/ -f1 | rev)"
        echo $VERSIONED_FILE
        zip $VERSIONED_FILE manifest.json content_script.js options/*
        gh release create $VERSIONED_FILE $VERSIONED_FILE
